FROM node:16 AS builder

WORKDIR /client

COPY . .
RUN rm -rf node_modules
RUN rm -rf .next
RUN rm -rf package-lock.json

RUN npm install
RUN npm run build


FROM node:16

WORKDIR /client

COPY --from=builder /client  .

CMD ["npm", "run", "start"]