
version: "3.3"

services:

  ingress:
    image: sotig/bms_ingress:latest
    container_name: ${PROJECT_NAME}_ingress 
    build: 
      context: ./ingress
      dockerfile: Dockerfile 

  client:  
    image: sotig/bms_client:latest
    container_name: ${PROJECT_NAME}_client 
    build: 
      context: ./client
      dockerfile: Dockerfile.prod 

  server:  
    image: sotig/bms_server:latest
    container_name: ${PROJECT_NAME}_server 
    build: 
      context: ./server
      dockerfile: Dockerfile.prod  